Repository schizofox/schizofox, pull requests merged in 2023-12, with the labels that each got.

#55 feat: paint firefox ui with user's colors
  modules/hm/firefox/preferences/default.nix
  modules/hm/firefox/userContent.nix
  modules/hm/options/theme.nix
Labels: new-feature

#57 refactor: restructure some options
  .github/README.md
  modules/hm/firefox/extensions/default.nix
  modules/hm/firefox/userChrome.nix
  modules/hm/options/extensions.nix
  modules/hm/options/renamed.nix
  modules/hm/options/theme.nix
Labels: breaking-change

#58 refactor: cleanup
  modules/hm/default.nix
  modules/hm/firefox/preferences/default.nix
  modules/hm/firefox/userChrome.nix
  modules/hm/firefox/userContent.nix
  pkgs/simplefox/userChrome.nix
  pkgs/simplefox/userContent.nix
Labels: documentation, enhancement, refactor

#64 fixes, add primary and border colors
  modules/hm/default.nix
  modules/hm/firefox/preferences/default.nix
  modules/hm/firefox/userChrome.nix
  modules/hm/firefox/userContent.nix
  modules/hm/options/theme.nix
  pkgs/simplefox/patches/0001-add-font-config.patch
  pkgs/simplefox/userChrome.nix
  pkgs/simplefox/userContent.nix
Labels: enhancement

#65 flake: remove nmd input
  flake.lock
  flake.nix
Labels: cleanup, dependencies

#71 fix: drmFix option
  modules/hm/firefox/preferences/default.nix
Labels: bugfix

#72 Remove -Profile flag from wrapper
  modules/hm/firefox/default.nix
Labels: bugfix, cleanup
