Repository schizofox/schizofox, pull requests merged in 2024-06, with the labels that each got.

#105 flake: update inputs
  flake.lock
Labels: maintenance

#106 feat: add contextMenu option
  .github/README.md
  modules/home-manager/firefox/preferences/default.nix
  modules/home-manager/options/misc.nix
Labels: enhancement, priority-medium

#110 Security & Privacy Improvements
  flake.lock
  flake.nix
  flake/lib/default.nix
  flake/lib/extensions/default.nix
  flake/modules/default.nix
  flake/modules/home-manager/default.nix
  flake/modules/home-manager/engineList.nix
  flake/modules/home-manager/firefox/default.nix
  flake/modules/home-manager/firefox/extensions/default.nix
  flake/modules/home-manager/firefox/preferences/default.nix
  flake/modules/home-manager/firefox/userChrome.nix
  flake/modules/home-manager/firefox/userContent.nix
  flake/modules/home-manager/options/default.nix
  flake/modules/home-manager/options/extensions.nix
  flake/modules/home-manager/options/general.nix
  flake/modules/home-manager/options/misc.nix
  flake/modules/home-manager/options/renamed.nix
  flake/modules/home-manager/options/search.nix
  flake/modules/home-manager/options/security.nix
  flake/modules/home-manager/options/theme.nix
  flake/pkgs/darkreader.nix
  flake/pkgs/default.nix
  flake/pkgs/simplefox/patches/0001-add-font-config.patch
  flake/pkgs/simplefox/userChrome.nix
  flake/pkgs/simplefox/userContent.nix
  flake/tests/checks/basic.nix
  flake/tests/checks/nixpak.nix
  flake/tests/default.nix
  flake/tests/profiles/test-setup.nix
  lib/default.nix
  lib/extended-lib.nix
  modules/home-manager/firefox/extensions/default.nix
  modules/home-manager/options/extensions.nix
Labels: major, cleanup, breaking-change, priority-critical
