Repository schizofox/schizofox, pull requests merged in 2024-04, with the labels that each got.

#93 CI: checkout with repo secret
  .github/workflows/update.yml
  flake.lock
Labels: bugfix, ci

#95 feat: add option to enable firefox sync
  modules/home-manager/firefox/default.nix
  modules/home-manager/options/misc.nix
Labels: enhancement, minor, new-feature, priority-medium

#98 fix: remove deprecated .desktop category
  modules/home-manager/firefox/default.nix
Labels: enhancement, minor, bugfix
